services:

  postgres:
    image: postgres:17

    container_name: epss-postgres

    environment:
      POSTGRES_DB: epss
      POSTGRES_USER: epss_user
      POSTGRES_PASSWORD: epss_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: